[api_keys]
coinmarketcap = "7a4be8a4-d432-4d70-84b5-4ce749f3040b"
gemini = "AIzaSyDW-aDLbt8CN2DrvwWtKPewdYVLf4VqBtM"

# The URLs are also sensitive and should be configured as secrets
# The production URL for live data
coinmarketcap_latest_listings_url = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest"
coinmarketcap_historical_url = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/ohlcv/historical"
coinmarketcap_global_metrics_url = "https://pro-api.coinmarketcap.com/v1/global-metrics/quotes/latest"


# .streamlit/secrets.toml

cmc_api_key = "7a4be8a4-d432-4d70-84b5-4ce749f3040b"
gemini_api_key = "AIzaSyDW-aDLbt8CN2DrvwWtKPewdYVLf4VqBtM"
